version: "3.1"
networks:
  aa:
    driver: bridge
services:
  mongo:
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    networks:
      - aa
    volumes:
      - ./db:/data/db
    # network_mode: host
  web:
    command: npm run production
    container_name: next-docker-production
    environment:
      NEXTAUTH_SECRET: pR6BGKqs/EF1WrbfNdw98Y/hBa8It5wOjmsej3ZF220=
      # DATABASE_URL: mongodb://admin:password@mongo:27017/db?authSource=admin
      DATABASE_URL: mongodb+srv://Prisma:idr8Se7IFGQbpBLh@cluster0.2tnkjsr.mongodb.net/mydb?retryWrites=true&w=majority
      GOOGLE_CLIENT_ID: 834755766051-ossb8mkr5pont9plkkt2ln3sgi9b48af.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - aa
    build: .
# networks:
#   NETWORK:
#     external: true
# networks:
#   some-net:
#     driver: bridge
#   front_some-net:
#     driver: bridge
