import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import ProvidersWrapper from "./ProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <ProvidersWrapper>
        <Navbar />
        {children}
        </ProvidersWrapper>
       
      </body>
    </html>
  );
}
